export ZSH=${HOME}/.oh-my-zsh

ZSH_THEME="zeus"

CASE_SENSITIVE="true"
HYPHEN_INSENSITIVE="true"
DISABLE_AUTO_UPDATE="true"
COMPLETION_WAITING_DOTS="true"

plugins=( z git sudo zsh-syntax-highlighting zsh-autosuggestions zsh-history-substring-search )

# Defaults
export EDITOR='vim'
export TERM="xterm-256color"
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=60"

# ZSH Completions
source ${ZSH}/oh-my-zsh.sh
source ${HOME}/.zsh_coding
source ${HOME}/.zsh_custom